### ISSUE TITLE
gulp extend search npm search is not finding some packages

### ISSUE THREAD

**Issue by paulocfjunior** [liferay/liferay-themes-sdk#25]
**package**: liferay-theme-tasks
**version**: 8.0.0-beta.1

I've published some themelets and tried to extend a theme using them, but they doesn't appear on the search performed by gulp extend > Themelet > Search npm registry (published modules).
The task didn't returned an error, only said "No themelets matched your search!".

The packages I tried to use were:
- [efx-buttons-themelet](https://www.npmjs.com/package/efx-buttons-themelet);
- [javascript-demo-themelet](https://www.npmjs.com/package/javascript-demo-themelet); and
- [javascript-demo-2-themelet](https://www.npmjs.com/package/javascript-demo-2-themelet).

These packages were created by using Yeoman generator and have the keyword 'liferay-theme'.

**Comment by paulocfjunior** [comment]
Realized that npm search API may not show new packages instantly. javascript demos themelets are now showing on search, after a few days from their publication, but the efx-buttons-themelet aren't showing yet.

(With #26 tested locally, was possible to find them all and recently published packages too)

**Comment by izaera** [comment]
@paulocfjunior This is working for me:

<img width="836" alt="imagen" src="https://user-images.githubusercontent.com/3273630/43128355-1a428860-8f32-11e8-9706-0ef4d2d248d9.png">

The problem may be that the theme where you are running the `extend` is targeting Liferay `7.1` and the themelets are published for `7.0`. Can you check that, please? 

Thanks.

**Comment by paulocfjunior** [comment]
Hi @izaera, thanks for the review. I'm using a theme for Liferay 7.0, there was a problem with the npm search, it wasn't able to find recently published packages but seems now it was fixed and it is working here too. I think we can close this issue / PR.

**Comment by jbalsas** [comment]
Thanks @paulocfjunior! Please, continue reporting any issues you find!

I've filed https://github.com/liferay/liferay-themes-sdk/issues/31 for a small improvement about the information we show. Hopefully that should at least help a little.

**Comment by izaera** [comment]
See issue #31 too.

**Comment by fortunatomaldonado** [comment]
Hello @izaera,

I am still receiving this error but this may be due to my configs. Do you mind telling me which version of nodejs/npm you are currently using? I also followed the README to set the dependencies, is there anything else that needs to be done to use these tools?
Thank you for your help!
